[build-system]
requires = [
    "hatchling",
    "hatch-conda",
    "hatch-vcs",
    "bleach",
    "bokeh >=3.1.0,<3.2.0",
    "cryptography <39",
    "packaging",
    "param >=1.9.2",
    "pyct >=0.4.4",
    "pyviz_comms >=0.7.4",
    "requests",
    "tqdm >=4.48.0",
]
build-backend = "hatchling.build"

[project]
name = "panel"
dynamic = ["version"]
description = "A high level app and dashboarding solution for Python."
readme = "README.md"
license = { file = "LICENSE.txt" }
requires-python = ">=3.8"
authors = [
    { name = "HoloViz", email = "developers@holoviz.org" },
]
maintainers = [
    { name = "HoloViz", email = "developers@holoviz.org" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Legal Industry",
    "Intended Audience :: Other Audience",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Office/Business",
    "Topic :: Office/Business :: Financial",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Libraries",
]
dependencies = [
    "bleach",
    "bokeh >=3.1.0,<3.2.0",
    "markdown",
    "pandas >=1.2",
    "param >=1.12.0",
    "pyct >=0.4.4",
    "pyviz_comms >=0.7.4",
    "requests",
    "setuptools >=42",
    "tqdm >=4.48.0",
    "typing_extensions",
]

[project.optional-dependencies]
all = [
    "panel[doc]",
    "panel[examples]",
    "panel[recommended]",
    "panel[tests]",
    "panel[ui]"
]
build = [
    "panel"
]
doc = [
    "nbsite >=0.8.0rc7",
    "pydata-sphinx-theme ==0.9.0",
    "sphinx-copybutton",
    "sphinx-design",
]
examples = [
    "aiohttp",
    "altair",
    "channels",
    "croniter",
    "diskcache",
    "django <4",
    "folium",
    "graphviz",
    "ipyleaflet",
    "ipympl",
    "ipyvolume",
    "ipyvuetify",
    "ipywidgets",
    "ipywidgets_bokeh",
    "jupyter_bokeh >=3.0.2",
    "lxml",
    "networkx >=2.5",
    "plotly >=4.0",
    "pydeck",
    "pyecharts",
    "pyinstrument >=4.0",
    "reacton",
    "scipy",
    "scikit-image",
    "scikit-learn",
    "seaborn",
    "streamz",
    "vega_datasets",
    "xarray",
]
pip-extras = [
    "ipywidgets_bokeh",
    "playwright",
    "pydeck",
    "pyecharts",
    "pytest-playwright",
    "reacton",
    "vega_datasets",
]
conda-extras = [
    "python-graphviz",
    "vtk==9.0.1",
    "xgboost"
]
recommended = [
    "holoviews >=1.16.0a2",
    "hvplot",
    "jupyterlab",
    "matplotlib",
    "pandas >=1.3",
    "pillow",
    "plotly",
]
tests = [
    "flake8",
    "flaky",
    "ipython >=7.0",
    "lxml",
    "markdown-it-py",
    "nbval",
    "parameterized",
    "pre-commit",
    "psutil",
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "twine",
]
ui = [
    "playwright",
    "pytest-playwright",
]

[project.scripts]
panel = "panel.command:main"

[project.urls]
Homepage = "http://panel.holoviz.org"
Source = "https://github.com/holoviz/panel"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.custom]

[tool.hatch.build]
ignore-vcs = true

[tool.hatch.build.targets.wheel.shared-data]
"jupyter-config/jupyter_notebook_config.d" = "etc/jupyter/jupyter_notebook_config.d"
"jupyter-config/jupyter_server_config.d" = "etc/jupyter/jupyter_server_config.d"

[tool.hatch.build.targets.sdist]
include = [
    "/panel"
]

[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    ".tox",
    ".eggs",
    "*.egg",
    "doc",
    "dist",
    "build",
    "_build",
    "examples",
    ".ipynb_checkpoints",
    "node_modules",
    "apps",
]
ignore = [
    "E402",
    "E712",
    "E731",
    "E741",
    "W605"
]
line-length = 165
select = [
    "E",
    "F",
    "W",
]

[tool.ruff.per-file-ignores]
"panel/tests/ui/jupyter_server_test_config.py" = ["F821"]

[tool.isort]
force_grid_wrap = 4
multi_line_output = 5
combine_as_imports = true
lines_between_types = 1
include_trailing_comma = true

[tool.pytest.ini_options]
addopts = "-v --pyargs --doctest-ignore-import-errors"
norecursedirs = "doc .git dist build _build .ipynb_checkpoints panel/examples"
xfail_strict = true
